name: LMS CI/CD

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1 - Checkout code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2 - Log in to Azure using client secret JSON
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Step 3 - Build Docker image (Dockerfile inside 'library-management-system/')
    - name: Build Docker image
      run: |
        docker build -t lmsacr001.azurecr.io/lms:latest ./library-management-system

    # Step 4 - Log in to Azure Container Registry
    - name: Log in to ACR
      run: |
        az acr login --name lmsacr001

    # Step 5 - Push Docker image to ACR
    - name: Push Docker image
      run: |
        docker push lmsacr001.azurecr.io/lms:latest

    # Step 6 - Deploy to Azure Container App
    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: lms-app
    #     images: lmsacr001.azurecr.io/lms:latest

    - name: Deploy to Azure Container App
      run: |
        az containerapp update \
          --name lms123 \
          --resource-group LIB1 \
          --image ${{ secrets.ACR_NAME }}.azurecr.io/lms:latest \
          --registry-server ${{ secrets.ACR_NAME }}.azurecr.io
